[project]
name = "LF-Certi-Prep-QnA-MCP-Server"
version = "0.1.0"
description = "LF Certification Preparation QnA MCP server"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.9.0",
    "pandas>=2.2.3",
    "sqlite-vec>=0.1.6",
]
